name: betris
version: 0.2.0.0
github: "mlang/betris"
license: BSD3
author: "Mario Lang"
maintainer: "mlang@blind.guru"
copyright: "2020 Mario Lang"

extra-source-files:
- README.md

synopsis: A horizontal version of tetris for braille users
category: Game
description: The game of tetris for braille display users, implemented using
  unicode braille rotated 90 degrees.  Tetriminos are "falling" from right to
  left.

tested-with: GHC == 8.0.1, GHC == 8.4.3
ghc-options: -Wall

dependencies:
- ansi-terminal
- base                 >= 4.9.0 && < 4.15
- containers           >= 0.5.7 && < 0.7
- lens                 >= 4.15.4 && < 4.20
- linear               >= 1.20.7 && < 1.22
- optparse-applicative >= 0.14.2 && < 0.16
- random               >= 1.1 && < 1.2
- stm                  >= 2.4.5 && < 2.6
- time-units           >= 1.0.0 && < 1.1
- vty                  >= 5.21 && < 5.33

library:
  source-dirs: src

executables:
  betris:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - betris
