name:                betris
version:             0.1.0.2
github:              "mlang/betris"
license:             BSD3
author:              "Mario Lang"
maintainer:          "mlang@blind.guru"
copyright:           "2018 Mario Lang"

extra-source-files:
- README.md

synopsis:            Braille friendly horizontal version of tetris
category:            Game

description:         Please see the README at <https://github.com/mlang/betris#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- lens
- linear
- optparse-applicative
- random
- stm
- stm-chans
- vty

library:
  source-dirs: src

executables:
  betris:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - betris
